### ISSUE TITLE
Tag versions when publishing to npm?

### ISSUE THREAD

**Issue by hdgarrood** [ThomasCrevoisier/psvm-js#18]
It would be nice to add a git tag for each version you publish to npm - for example, this makes it easier to diagnose issues, as people can easily look at the code they're running. In case you weren't aware, `npm version` can do this for you and update package.json properly at the same time, too.

**Comment by ThomasCrevoisier** [comment]
Yep I agree. I didn't do that for the moment as it was a beta. I thought about releasing a new version when #7 will be solved.

**Comment by hdgarrood** [comment]
Ahh, makes sense.
