### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by hdgarrood** [ThomasCrevoisier/psvm-js#26]
Would you be ok with adding support for Windows? I'd be happy to make the code changes required; I'm expecting (hoping) that they'll be relatively straightforward.

**Comment by ThomasCrevoisier** [comment]
Yep absolutely. I wouldn't be able to test though as I am mostly on Linux and Mac :/

What changes do you have in mind ? The use of `os.homedir()` ?

**Comment by hdgarrood** [comment]
I am not sure exactly, I was going to just try it and see if anything broke. I don't think psvm uses `os.homedir` anywhere at the moment; it even seems like `paths.js` was written with eventual Windows support in mind: https://github.com/ThomasCrevoisier/psvm-js/blob/111dffa9fc5988f54d52fbc87646d2e00f166ee8/src/paths.js

**Comment by hdgarrood** [comment]
Fixed by #27.
